version: '3.9'

services:
  app:
    build: .
    ports:
      - "8081:8888"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: customers
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    ports:
      - "8080:8080"
